### ISSUE TITLE
Investigate bootstrapping for data without Kriging

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopop#50] opened 2022-12-06 17:24 UTC
In PR #32 we implemented bootstrapping for data with and without Kriging. As noted in https://github.com/uw-echospace/EchoPro/pull/32#issuecomment-1289834510 there is a large difference in the output of mean total biomass density between the data with Kriging and without it. Part of this difference may be due to the fact that there are more mesh points in the data with Kriging. However, the main portion of this code that needs to be investigated is that it appears that the bootstrapping is occurring on the `areal_biomass_density_adult`, rather than the total biomass estimate (which is being used for the bootstrapping with Kriging). If this is true, we need to change this so that bootstrapping is occurring on the total biomass estimate produced without Kriging.

**Comment by emiliom** [comment] 2023-09-20 22:58
It looks like PR #89 addressed the last item in the comment immediately above. Once I've confirmed this, this issue can be closed (but document any important points elsewhere).

**Comment by leewujung** [comment] 2023-10-31 15:13
Can this be closed now with the new issue #95?

**Comment by emiliom** [comment] 2023-12-08 10:29
Yes, let's close this and track the issues with transect selection in #95

**Closed as completed by emiliom** 2023-12-08 10:29 UTC
Labels: bug_in_python
